### ISSUE TITLE
Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view CameraPreviewMauiSample.CustomControl.CameraView.'

### ISSUE THREAD

**Issue by JuLights** [danielftz/MCT-CameraView-Demo#1]
I'm getting error when I try to run it, I'm new in mobile development and trying to figure it out how to fix it, I know, I need Handler for View.
![image](https://user-images.githubusercontent.com/52431123/212333518-e69b4b2c-b63d-4329-908f-34bec827b47b.png)

**Comment by danielftz** [comment]
My current implementation of CameraView uses the Handler architecture as opposed to the legacy Renderer architecture in the repo. I will update it this weekend.

**Comment by danielftz** [comment]
Has the new version been working fine for you?
